/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Classes.*;
import Conexão.*;
import javax.swing.*;
/**
 *
 * @author Victor
 */
public class CadastroTrabalhador extends javax.swing.JFrame {
    String login, senha;
    /**
     * Creates new form CadastroTrabalhador
     */
    public CadastroTrabalhador(String login, String senha) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.login = login;
        this.senha = senha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        endereçoTexto = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        cpfTexto = new javax.swing.JLabel();
        dataNascimentoTexto = new javax.swing.JLabel();
        dataNascimento = new javax.swing.JFormattedTextField();
        nome = new javax.swing.JTextField();
        usuarioTexto = new javax.swing.JLabel();
        telefoneTexto = new javax.swing.JLabel();
        especialidadeTexto = new javax.swing.JLabel();
        descriçãoTexto = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        endereço = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        descrição = new javax.swing.JTextArea();
        especialidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T-Work");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        confirmar.setText("CADASTRAR");
        confirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 100, 30));

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        voltar.setOpaque(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        endereçoTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        endereçoTexto.setText("ENDEREÇO: ");
        getContentPane().add(endereçoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 24));

        cpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 163, 210, 22));

        cpfTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cpfTexto.setText("CPF:");
        getContentPane().add(cpfTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 50, 24));

        dataNascimentoTexto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dataNascimentoTexto.setText("DATA DE NASCIMENTO: ");
        getContentPane().add(dataNascimentoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 24));

        dataNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            dataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(" ##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(dataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 131, 150, 24));

        nome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, -1));

        usuarioTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usuarioTexto.setText("NOME:");
        getContentPane().add(usuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 24));

        telefoneTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        telefoneTexto.setText("TELEFONE: ");
        getContentPane().add(telefoneTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 24));

        especialidadeTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        especialidadeTexto.setText("ESPECIALIDADES:");
        getContentPane().add(especialidadeTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, 24));

        descriçãoTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        descriçãoTexto.setText("DESCRIÇÃO:");
        getContentPane().add(descriçãoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 24));

        telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 209, 22));

        endereço.setColumns(20);
        endereço.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        endereço.setRows(5);
        endereço.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(endereço);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 210, 80));

        descrição.setColumns(20);
        descrição.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        descrição.setRows(5);
        descrição.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(descrição);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 316, 210, 101));

        especialidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        especialidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(especialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 330, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("palavras-chave, apenas.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telawhatever.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        String usu = login;
        String sen = senha;
        
        String name = nome.getText();
        String dtN = dataNascimento.getText();
        String CPF = cpf.getText();
        String ende = endereço.getText();
        String tele = telefone.getText();
        String desc = descrição.getText();
        String espe = especialidade.getText();
        
        if(nome.equals("") || dataNascimento.equals("") || cpf.equals("") ||
                endereço.equals("") || telefone.equals("") || descrição.equals("") ||
                especialidade.equals("")){
            JOptionPane.showMessageDialog(null, "Campos não preenchidos");
        }else{
            Trabalhador trab = new Trabalhador(usu, sen, name, dtN, ende, CPF, tele, desc, espe);
            TrabalhadorDao trabDao = new TrabalhadorDao();
            trabDao.salvar(trab);
            new Inicial().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_confirmarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new Cadastro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JLabel cpfTexto;
    private javax.swing.JFormattedTextField dataNascimento;
    private javax.swing.JLabel dataNascimentoTexto;
    private javax.swing.JTextArea descrição;
    private javax.swing.JLabel descriçãoTexto;
    private javax.swing.JTextArea endereço;
    private javax.swing.JLabel endereçoTexto;
    private javax.swing.JTextField especialidade;
    private javax.swing.JLabel especialidadeTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nome;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JLabel telefoneTexto;
    private javax.swing.JLabel usuarioTexto;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
