/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Victor
 */
public class Cadastro extends javax.swing.JFrame {
    int i=0;
    String login, pass;
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        voltar = new javax.swing.JButton();
        prox = new javax.swing.JButton();
        usuarioTexto = new javax.swing.JLabel();
        senhaTexto = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        empresa = new javax.swing.JRadioButton();
        trabalhador = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T-Work");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        voltar.setOpaque(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        prox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        prox.setText("SEGUINTE");
        prox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxActionPerformed(evt);
            }
        });
        getContentPane().add(prox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 100, 30));

        usuarioTexto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usuarioTexto.setText("USUÁRIO: ");
        getContentPane().add(usuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 24));

        senhaTexto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        senhaTexto.setText("SENHA:");
        getContentPane().add(senhaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 93, 24));

        usuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 190, -1));

        senha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        senha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 190, -1));

        buttonGroup1.add(empresa);
        empresa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        empresa.setText("EMPRESA");
        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });
        getContentPane().add(empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 129, -1));

        buttonGroup1.add(trabalhador);
        trabalhador.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        trabalhador.setText("TRABALHADOR");
        trabalhador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabalhadorActionPerformed(evt);
            }
        });
        getContentPane().add(trabalhador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        i = 2;
    }//GEN-LAST:event_empresaActionPerformed

    private void proxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxActionPerformed
        if(i==1){
            login = usuario.getText();
            pass = new String(senha.getPassword());
            new CadastroTrabalhador(login,pass).setVisible(true);
            setVisible(false);
        }
        if(i==2){
            login = usuario.getText();
            pass = new String(senha.getPassword());
            new CadastroEmpresa(login,pass).setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_proxActionPerformed

    private void trabalhadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabalhadorActionPerformed
        i = 1;
    }//GEN-LAST:event_trabalhadorActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new Inicial().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton empresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton prox;
    private javax.swing.JPasswordField senha;
    private javax.swing.JLabel senhaTexto;
    private javax.swing.JRadioButton trabalhador;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuarioTexto;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
