/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import Classes.*;
import Conexão.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Victor
 */
public class CadastroEmpresa extends javax.swing.JFrame {
    String login, senha;
    /**
     * Creates new form CadastroEmpresa
     */
    public CadastroEmpresa(String login, String senha) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.login = login;
        this.senha = senha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();
        usuarioTexto = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        dataAberturaTexto = new javax.swing.JLabel();
        dataAbertura = new javax.swing.JFormattedTextField();
        cnpjTexto = new javax.swing.JLabel();
        cnpj = new javax.swing.JFormattedTextField();
        endereçoTexto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        endereço = new javax.swing.JTextArea();
        telefoneTexto = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        descriçãoTexto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descrição = new javax.swing.JTextArea();
        necessidadeTexto = new javax.swing.JLabel();
        necessidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        usuarioTexto1 = new javax.swing.JLabel();
        vagas = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T-Work");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        voltar.setOpaque(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        confirmar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        confirmar.setText("CADASTRAR");
        confirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 100, 30));

        usuarioTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usuarioTexto.setText("NOME:");
        getContentPane().add(usuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 24));

        nome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 270, 20));

        dataAberturaTexto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dataAberturaTexto.setText("DATA DE ABERTURA: ");
        getContentPane().add(dataAberturaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 24));

        dataAbertura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            dataAbertura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(" ##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataAbertura.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(dataAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 160, 24));

        cnpjTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cnpjTexto.setText("CNPJ:");
        getContentPane().add(cnpjTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 24));

        cnpj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpj.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 270, 22));

        endereçoTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        endereçoTexto.setText("ENDEREÇO: ");
        getContentPane().add(endereçoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 24));

        endereço.setColumns(20);
        endereço.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        endereço.setRows(5);
        endereço.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(endereço);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 230, 80));

        telefoneTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        telefoneTexto.setText("TELEFONE: ");
        getContentPane().add(telefoneTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 24));

        telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 250, 230, 22));

        descriçãoTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        descriçãoTexto.setText("DESCRIÇÃO:");
        getContentPane().add(descriçãoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 24));

        descrição.setColumns(20);
        descrição.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        descrição.setRows(5);
        descrição.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(descrição);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 230, 101));

        necessidadeTexto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        necessidadeTexto.setText("NECESSIDADE:");
        getContentPane().add(necessidadeTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, 24));

        necessidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        necessidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(necessidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 330, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("palavras-chave, apenas.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        usuarioTexto1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usuarioTexto1.setText("Nº DE VAGAS:");
        getContentPane().add(usuarioTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, 24));

        vagas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vagas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(vagas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telawhatever.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        String usu = login;
        String pass = senha;
        
        String name = nome.getText();
        String dtA = dataAbertura.getText();
        String ende = endereço.getText();
        String CNPJ = cnpj.getText();
        String tele = telefone.getText();
        String desc = descrição.getText();
        String nece = necessidade.getText();
        
        String aux = vagas.getText();
        int vaga = Integer.parseInt(aux);
        
        if(nome.equals("") || dataAbertura.equals("") || cnpj.equals("") ||
                endereço.equals("") || telefone.equals("") || descrição.equals("") ||
                necessidade.equals("") || vagas.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campos não preenchidos");
        }else{
            Empresa empresa = new Empresa(usu, pass, name, dtA, ende, CNPJ, tele, desc, nece, vaga);
            EmpresaDao empresaDao = new EmpresaDao();
            empresaDao.salvar(empresa);
            new Inicial().setVisible(true);
            setVisible(false);
        }
           
    }//GEN-LAST:event_confirmarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new Cadastro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JLabel cnpjTexto;
    private javax.swing.JButton confirmar;
    private javax.swing.JFormattedTextField dataAbertura;
    private javax.swing.JLabel dataAberturaTexto;
    private javax.swing.JTextArea descrição;
    private javax.swing.JLabel descriçãoTexto;
    private javax.swing.JTextArea endereço;
    private javax.swing.JLabel endereçoTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField necessidade;
    private javax.swing.JLabel necessidadeTexto;
    private javax.swing.JTextField nome;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JLabel telefoneTexto;
    private javax.swing.JLabel usuarioTexto;
    private javax.swing.JLabel usuarioTexto1;
    private javax.swing.JTextField vagas;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
