/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Conexão.*;
import Classes.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class Login extends javax.swing.JFrame {
    int i;
    String usu, pass;
    /**
     * Creates new form Login
     */
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        usuario.setText("");
        senha.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        voltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        empresa = new javax.swing.JRadioButton();
        entrar = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        usuario = new javax.swing.JTextField();
        senhaTexto = new javax.swing.JLabel();
        trabalhador = new javax.swing.JRadioButton();
        usuarioTexto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T-Work");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        voltar.setOpaque(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(empresa);
        empresa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        empresa.setText("EMPRESA");
        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });
        jPanel2.add(empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 129, -1));

        entrar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        entrar.setText("ENTRAR");
        entrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        jPanel2.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 80, 30));

        senha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        senha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        jPanel2.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 180, -1));

        usuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 180, -1));

        senhaTexto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        senhaTexto.setText("SENHA:");
        jPanel2.add(senhaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 93, 24));

        buttonGroup1.add(trabalhador);
        trabalhador.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        trabalhador.setText("TRABALHADOR");
        trabalhador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabalhadorActionPerformed(evt);
            }
        });
        jPanel2.add(trabalhador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        usuarioTexto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usuarioTexto.setText("USUÁRIO: ");
        jPanel2.add(usuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, 24));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/login.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        if(usuario.getText().equals("") || senha.getPassword().equals("")){
            JOptionPane.showMessageDialog(null, "Campos vazios.");
        }else{
            if(trabalhador.isSelected()){
            TrabalhadorDao trabDao = new TrabalhadorDao();
        
            usu = usuario.getText();
            pass = new String(senha.getPassword());
        
            Trabalhador trab = trabDao.consultar(usu,pass);
            
            if(trab==null){
                JOptionPane.showMessageDialog(null, "Usuário inexistente.");
            }else{
                new TelaTrabalhador(trab).setVisible(true);
                setVisible(false);
            }
            }
            
            if(empresa.isSelected()){
            EmpresaDao empresaDao = new EmpresaDao();
        
            usu = usuario.getText();
            pass = new String(senha.getPassword());
        
            Empresa em = empresaDao.consultar(usu,pass);
            
            if(em==null){
                JOptionPane.showMessageDialog(null, "Usuário inexistente.");
            }else{
                new TelaEmpresa(em).setVisible(true);
                setVisible(false);
            }
        }
            
        }
    }//GEN-LAST:event_entrarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new Inicial().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void trabalhadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabalhadorActionPerformed
        i = 1;
    }//GEN-LAST:event_trabalhadorActionPerformed

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        i = 2;
    }//GEN-LAST:event_empresaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton empresa;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField senha;
    private javax.swing.JLabel senhaTexto;
    private javax.swing.JRadioButton trabalhador;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuarioTexto;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
