/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Trabalhador;
import java.awt.Color;
import static java.awt.Color.GREEN;

/**
 *
 * @author ALUNO
 */
public class StatusTrabalhador extends javax.swing.JFrame {

    Trabalhador trab;
    
    public StatusTrabalhador(Trabalhador trab) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.trab = trab;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        aceitar = new javax.swing.JToggleButton();
        terminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        voltar.setOpaque(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        tabela1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nome", "CNPJ", "Endereço", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tabela1AncestorRemoved(evt);
            }
        });
        jScrollPane5.setViewportView(tabela1);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 80));

        aceitar.setBackground(new java.awt.Color(255, 255, 255));
        aceitar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        aceitar.setText("ACEITAR");
        aceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceitarActionPerformed(evt);
            }
        });
        jPanel1.add(aceitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 100, 20));

        terminar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        terminar.setText("Terminar");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });
        jPanel1.add(terminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/status.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new TelaTrabalhador(trab).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    int i=0;
    int aux=0;
    private void aceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceitarActionPerformed
        i++;
        if(i%2==0){
            aceitar.setBackground(Color.RED);
        }else{
            aceitar.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_aceitarActionPerformed

    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed
        new TelaTrabalhador(trab).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_terminarActionPerformed

    private void tabela1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabela1AncestorRemoved
        
    }//GEN-LAST:event_tabela1AncestorRemoved
    //split
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton aceitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabela1;
    private javax.swing.JButton terminar;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
