/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Classes.*;
/**
 *
 * @author aluno
 */
public class TelaEmpresa extends javax.swing.JFrame {

    Empresa emp;
    
    public TelaEmpresa(Empresa em) {
        initComponents();
        this.setLocationRelativeTo(null);
        nome.setEnabled(false);
        cnpj.setEnabled(false);
        
        emp=em;
        nome.setText(""+em.getNome());
        cnpj.setText(""+em.getCnpj());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nome = new javax.swing.JTextField();
        nomeTexto2 = new javax.swing.JLabel();
        cpfTexto = new javax.swing.JLabel();
        cnpj = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        atualizar = new javax.swing.JButton();
        status1 = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel2.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 340, 30));

        nomeTexto2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nomeTexto2.setText("NOME:");
        nomeTexto2.setToolTipText("");
        jPanel2.add(nomeTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        cpfTexto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cpfTexto.setText("CNPJ:");
        cpfTexto.setToolTipText("");
        jPanel2.add(cpfTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 30));

        cnpj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpj.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });
        jPanel2.add(cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 340, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("SEJA BEM VINDO!");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        atualizar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        atualizar.setText("ATUALIZAR DADOS");
        atualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        jPanel2.add(atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 200, 40));

        status1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        status1.setText("STATUS");
        status1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status1ActionPerformed(evt);
            }
        });
        jPanel2.add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 90, 40));

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        voltar.setOpaque(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel2.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\projeto\\T-Work\\build\\classes\\Imagens\\cadastroEmpresa.jpeg")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed

    }//GEN-LAST:event_cnpjActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new Cadastro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status1ActionPerformed
        new StatusEmpresa(emp).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_status1ActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        new AtualizarEmpresa(emp).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JLabel cpfTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomeTexto2;
    private javax.swing.JButton status1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
