/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Classes.*;
/**
 *
 * @author aluno
 */
public class TelaTrabalhador extends javax.swing.JFrame {
    Trabalhador trab;
    /**
     * Creates new form TelaTrabalhador
     */
    public TelaTrabalhador(Trabalhador trab) {
        initComponents();
        this.setLocationRelativeTo(null);
        nome.setEnabled(false);
        idade.setEnabled(false);
        cpf.setEnabled(false);

        this.trab = trab;
        
        nome.setText(""+trab.getNome());
        cpf.setText(trab.getCpf());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        idade = new javax.swing.JTextField();
        nomeTexto2 = new javax.swing.JLabel();
        cpfTexto = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        idadeTexto = new javax.swing.JLabel();
        atualizar = new javax.swing.JButton();
        status1 = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 550));
        setMinimumSize(new java.awt.Dimension(650, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        nome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 340, 30));

        idade.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        idade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 40, 30));

        nomeTexto2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nomeTexto2.setText("NOME:");
        nomeTexto2.setToolTipText("");
        getContentPane().add(nomeTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        cpfTexto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cpfTexto.setText("CPF:");
        cpfTexto.setToolTipText("");
        getContentPane().add(cpfTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, 30));

        cpf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        getContentPane().add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 220, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("SEJA BEM VINDO!");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        idadeTexto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        idadeTexto.setText("IDADE:");
        idadeTexto.setToolTipText("");
        getContentPane().add(idadeTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 30));

        atualizar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        atualizar.setText("ATUALIZAR DADOS");
        atualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 200, 40));

        status1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        status1.setText("STATUS");
        status1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status1ActionPerformed(evt);
            }
        });
        getContentPane().add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 90, 40));

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        voltar.setOpaque(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 5, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 550));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroTrabalhador.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        
    }//GEN-LAST:event_cpfActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new Cadastro().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status1ActionPerformed
        new StatusTrabalhador(trab).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_status1ActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        new AtualizarTrabalhador(trab).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JLabel cpfTexto;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel idadeTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomeTexto2;
    private javax.swing.JButton status1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
